services:
  - type: web
    name: topicos-especiais-front
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    branch: main
    envVars:
      - key: VITE_API_URL
        sync: false
